package com.splitease.controller;

import com.splitease.dto.SettlementResponse;
import com.splitease.service.SettlementService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;

/**
 * Generates shareable settlement summaries for WhatsApp, text, etc.
 */
@RestController
@RequestMapping("/api/groups/{groupId}/share")
public class ShareController {

    private final SettlementService settlementService;

    public ShareController(SettlementService settlementService) {
        this.settlementService = settlementService;
    }

    /**
     * GET /api/groups/{groupId}/share/whatsapp
     * Returns a WhatsApp-formatted settlement summary text.
     */
    @GetMapping("/whatsapp")
    public ResponseEntity<Map<String, String>> getWhatsAppMessage(@PathVariable Long groupId) {
        List<SettlementResponse> settlements = settlementService.computeSettlements(groupId);

        StringBuilder sb = new StringBuilder();
        sb.append("🧾 *SplitEase Settlement Plan*\n\n");

        if (settlements.isEmpty()) {
            sb.append("✅ All settled! No transactions needed. 🎉\n");
        } else {
            sb.append("💰 *").append(settlements.size()).append(" transaction(s) needed:*\n\n");
            for (int i = 0; i < settlements.size(); i++) {
                SettlementResponse s = settlements.get(i);
                sb.append("  ").append(i + 1).append(". ")
                  .append(s.getFromUserName())
                  .append(" ➜ ")
                  .append(s.getToUserName())
                  .append(": *₹")
                  .append(s.getAmount().toPlainString())
                  .append("*\n");
            }
            sb.append("\n_Settle up and stay square!_ 🤝");
        }

        sb.append("\n\n_Generated by SplitEase_");

        Map<String, String> result = new LinkedHashMap<>();
        result.put("message", sb.toString());
        result.put("whatsappUrl", "https://wa.me/?text=" + encodeURIComponent(sb.toString()));
        return ResponseEntity.ok(result);
    }

    /**
     * GET /api/groups/{groupId}/share/text
     * Returns a plain-text settlement summary.
     */
    @GetMapping("/text")
    public ResponseEntity<Map<String, String>> getTextSummary(@PathVariable Long groupId) {
        List<SettlementResponse> settlements = settlementService.computeSettlements(groupId);

        StringBuilder sb = new StringBuilder();
        sb.append("SplitEase Settlement Plan\n");
        sb.append("========================\n\n");

        if (settlements.isEmpty()) {
            sb.append("All settled! No transactions needed.\n");
        } else {
            sb.append(settlements.size()).append(" transaction(s) needed:\n\n");
            for (int i = 0; i < settlements.size(); i++) {
                SettlementResponse s = settlements.get(i);
                sb.append("  ").append(i + 1).append(". ")
                  .append(s.getFromUserName())
                  .append(" -> ")
                  .append(s.getToUserName())
                  .append(": Rs.")
                  .append(s.getAmount().toPlainString())
                  .append("\n");
            }
        }

        Map<String, String> result = new LinkedHashMap<>();
        result.put("message", sb.toString());
        return ResponseEntity.ok(result);
    }

    private String encodeURIComponent(String text) {
        try {
            return java.net.URLEncoder.encode(text, "UTF-8")
                    .replace("+", "%20");
        } catch (Exception e) {
            return text;
        }
    }
}
